/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bancodemexico;

/**
 *
 * @author jorge.navidad
 */
public class SaldoJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SaldoJFrame.class.getName());

    /**
     * Creates new form SaldoJFrame
     */
    public SaldoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtTitulo = new javax.swing.JLabel();
        lblConsultar = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TxtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TxtTitulo.setText("Banco de México | Saldo");

        lblConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConsultar.setText("Ingrese cuenta");

        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtTitulo)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultar))
                .addGap(59, 59, 59)
                .addComponent(btnConsultar)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cuentaBuscada = txtConsultar.getText().trim();
    
    if (cuentaBuscada.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa el numero de cuenta.");
        return;
    }

    try {
        Conexion con = new Conexion();
        java.sql.Connection cn = con.conectar();
        
        if (cn != null) {
            // 1. Preparamos la consulta SQL
            String sql = "SELECT saldo_actual FROM cuenta WHERE id_cuenta = ?";
            java.sql.PreparedStatement pst = cn.prepareStatement(sql);
            
            // 2. Pasamos el ID de cuenta que el usuario escribio
            pst.setString(1, cuentaBuscada);
            
            // 3. Ejecutamos la consulta (executeQuery para SELECT)
            java.sql.ResultSet rs = pst.executeQuery();

            // 4. Verificamos si la cuenta existe
            if (rs.next()) {
                double saldo = rs.getDouble("saldo_actual");
                javax.swing.JOptionPane.showMessageDialog(this, "El saldo de la cuenta " + cuentaBuscada + " es: $" + saldo);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "La cuenta no existe en la base de datos.");
            }
            
            cn.close();
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El ID de cuenta debe ser numerico.");
    }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SaldoJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TxtTitulo;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JTextField txtConsultar;
    // End of variables declaration//GEN-END:variables
}
